version: "3.9"

services:
  frontend:
    image: harbor.codingpalette.net/library/blog-frontend
    ports:
      - "8080:3000"
    volumes:
      - blog_uploads/:/app/public/uploads
    environment:
      - NEXT_SSR_API_URL=${NEXT_SSR_API_URL}

  backend:
    image: harbor.codingpalette.net/library/blog-backend
    volumes:
      - blog_uploads/:/app/uploads/

    environment:
      NEST_CONFIG_DB_TYPE: ${NEST_CONFIG_DB_TYPE}
      NEST_CONFIG_DB_HOST: ${NEST_CONFIG_DB_HOST}
      NEST_CONFIG_DB_PORT: ${NEST_CONFIG_DB_PORT}
      NEST_CONFIG_DB_USER: ${NEST_CONFIG_DB_USER}
      NEST_CONFIG_DB_PASSWORD: ${NEST_CONFIG_DB_PASSWORD}
      NEST_CONFIG_DB_DATABASE_NAME: ${NEST_CONFIG_DB_DATABASE_NAME}
      NEST_CONFIG_DB_REDIS_HOST: ${NEST_CONFIG_DB_REDIS_HOST}
      NEST_CONFIG_DB_REDIS_PORT: ${NEST_CONFIG_DB_REDIS_PORT}
      NEST_CONFIG_AUTH_SECRET_JWT: ${NEST_CONFIG_AUTH_SECRET_JWT}
      NEST_CONFIG_UPLOADS_PATH: ${NEST_CONFIG_UPLOADS_PATH}
      NEST_CONFIG_APP_ROLE: ${NEST_CONFIG_APP_ROLE}
      NEST_ADMIN_USER_EMAIL: ${NEST_ADMIN_USER_EMAIL}
      NEST_ADMIN_USER_NAME: ${NEST_ADMIN_USER_NAME}
      NEST_ADMIN_USER_PASSWORD: ${NEST_ADMIN_USER_PASSWORD}
      NEST_CONFIG_CRON_STATUS: ${NEST_CONFIG_CRON_STATUS}
      NEST_SLACK_WEBHOOK: ${NEST_SLACK_WEBHOOK}
      NEST_NOTION_API_KEY: ${NEST_NOTION_API_KEY}
      NEST_NOTION_DATABASE_ID: ${NEST_NOTION_DATABASE_ID}

  redis:
    image: redis:6.2.6

  db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - blog_db:/var/lib/mysql

volumes:
  blog_backend_config: {}
  blog_uploads:
    external:
      name: blog_uploads
  blog_db:
    external:
      name: blog_db
