version: "3.9"

services:
  frontend:
    image: harbor.codingpalette.net/library/blog-frontend
    env_file: ./frontend/.env.test.local
    ports:
      - "3001:3000"
    volumes:
      - blog_uploads/:/app/public/uploads/

  backend:
    image: harbor.codingpalette.net/library/blog-backend
    volumes:
      - blog_uploads/:/app/uploads/
    env_file: ./backend/.env.stage
    depends_on:
      - db

  redis:
    image: redis:6.2.6

  db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    env_file: ./db/.env.stage
    volumes:
      - blog_db:/var/lib/mysql

volumes:
  blog_uploads: {}
  blog_db: {}
