version: "3.9"

services:
  frontend:
    build:
      target: development
      context: ./frontend
    volumes:
      - ./frontend/:/app/
    env_file: ./frontend/.env.test.local

  frontend_test:
    build:
      target: e2e
      context: ./frontend
    env_file: ./frontend/.env.test.local
    volumes:
      - ./frontend/cypress/screenshots:/app/cypress/screenshots
      - ./frontend/cypress/videos:/app/cypress/videos
    depends_on:
      - nginx
      - backend
      - frontend

  backend:
    build:
      target: development
      context: ./backend
    volumes:
      - ./backend/:/app/
      - ./storage/uploads/:/app/uploads/
    env_file: ./backend/.env.stage

  redis:
    image: redis:6.2.6
    ports:
      - "6379"

  db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306"
    env_file: ./db/.env.dev
    cap_add:
      - SYS_NICE
