version: "3.9"

services:
  nginx:
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      
  nginx-serve-static:
    build:
      context: ./nginx-serve-static/
    volumes:
      - ./storage/uploads/:/app/uploads/
      
  frontend:
    build:
      target: development
      context: ./frontend
    volumes:
      - ./frontend/:/app/
    env_file: .env.dev

  backend:
    build:
      target: development
      context: ./backend
    volumes:
      - ./backend/:/app/
      - ./storage/uploads/:/app/uploads/
    env_file: .env.dev

  backend_test:
    build:
      target: testing
      context: ./backend
    volumes:
      - ./backend/:/app/
    env_file: .env.dev

  redis:
    image: redis:6.2.6
    ports:
      - "6379"

  db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    env_file: .env.dev
    cap_add:
      - SYS_NICE

  db_test:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    env_file: .env.dev
    cap_add:
      - SYS_NICE