version: "3.9"

services:
  nginx:
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/front-only.conf:/etc/nginx/conf.d/default.conf
      - ./storage/uploads:/mnt/storage/uploads

  frontend:
    build:
      target: development
      context: .
      dockerfile: ./packages/frontend/Dockerfile
    volumes:
      - .:/app
    env_file: ./packages/frontend/.env.dev


  redis:
    image: redis:6.2.6
    ports:
      - "6379"

  backend:
    build:
      target: development
      context: .
      dockerfile: ./packages/backend/Dockerfile
    volumes:
      - .:/app
      - ./storage/uploads:/app/packages/backend/uploads
    environment:
      DB_URL: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: secret-pw
      DB_DATABASE_NAME: nest-blog
      SECRET_JWT: jA#()*%!@13
      REDIS_URL: redis
    env_file: ./packages/backend/.env.dev

  backend_test:
    build:
      target: testing
      context: .
      dockerfile: ./packages/backend/Dockerfile
    volumes:
      - .:/app
    environment:
      DB_HOST: db_test
      DB_PORT: 3306
      USER: root
      PASSWORD: secret-pw
      DATABASE: nest-blog
      SECRET_JWT: jA#()*%!@13
    env_file: ./packages/backend/.env.dev


  db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret-pw
      MYSQL_DATABASE: nest-blog
    cap_add:
      - SYS_NICE

  db_test:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret-pw
      MYSQL_DATABASE: nest-blog
    cap_add:
      - SYS_NICE
