version: "3.9"

services:
  nginx:
    volumes:
      - ./nginx/production.conf:/etc/nginx/conf.d/default.conf
      - ./storage/uploads:/mnt/storage/uploads

  frontend:
    build:
      target: production
      context: .
      dockerfile: ./packages/frontend/Dockerfile
    env_file: .env.prod

  backend:
    build:
      target: production
      context: .
      dockerfile: ./packages/backend/Dockerfile
    env_file: .env.prod
      
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      DB_URL: db

  db:
    command: --default-authentication-plugin=mysql_native_password
    env_file: ./.env.prod

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}