version: "3.9"

services:
  frontend:
    build:
      args:
        - NEXT_PRIVATE_SSR_API_URL="http://backend:3000"
        - NEXT_PUBLIC_CSR_API_URL="/api"
        - NEXT_PUBLIC_ALL_SERVE_STATIC_URL="/static"
        - NEXT_PUBLIC_ALL_IMAGE_PROVIDER="next"
        - NEXT_PUBLIC_ALL_HTTP_SCHEMA="http://"
        - NEXT_PUBLIC_ALL_IMAGE_HOST="nginx"