version: "3.9"

services:
  nginx:
    volumes:
      - ./nginx/production.conf:/etc/nginx/conf.d/default.conf
      - ./storage/uploads:/mnt/storage/uploads

  frontend:
    build:
      target: production
      context: .
      dockerfile: ./packages/frontend/Dockerfile
    # env_file: ./front/.env.prod

  backend:
    build:
      target: production
      context: .
      dockerfile: ./packages/backend/Dockerfile
    # env_file: ./back/.env.prod

  # db:
    # command: --default-authentication-plugin=mysql_native_password
    # environment:
      # MONGO_INITDB_DATABASE: dev
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: test

      # MYSQL_ROOT_PASSWORD: example
      # MYSQL_DATABASE: test

