version: "3.9"

services:
  nginx:
    volumes:
      - ./nginx/production.conf:/etc/nginx/conf.d/default.conf
      - ./storage/uploads:/mnt/storage/uploads

  front:
    build:
      target: production
      context: ./front
    # env_file: ./front/.env.prod

  back:
    build:
      target: production
      context: ./back
    # env_file: ./back/.env.prod

  db:
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      # MONGO_INITDB_DATABASE: dev
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: test

      # MYSQL_ROOT_PASSWORD: example
      # MYSQL_DATABASE: test

