version: "3.9"

services:
  frontend:
    build:
      target: development
      context: ./frontend
    volumes:
      - ./frontend/:/app/
    env_file: .env.dev
  backend:
    build:
      target: testing
      context: ./backend
    volumes:
      - ./backend/:/app/
      - ./storage/uploads/:/app/uploads/
    env_file: ./backend/.env.dev
    environment:
      - NEST_CONFIG_CRON_STATUS=false
  redis:
    image: redis:6.2.6
    ports:
      - "6379"
  db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306"
    env_file: ./db/.env.dev
    cap_add:
      - SYS_NICE
