version: "3.9"

services:
  nginx:
    volumes:
      - ./nginx/production.conf:/etc/nginx/conf.d/default.conf
  
  frontend:
    build:
      target: production
      context: ./frontend
    env_file: .env.test
        
  backend:
    build:
      target: production
      context: ./backend
    ports:
      - "3000:3000"
    env_file: .env.test
    volumes: 
      - ./storage/uploads/:/app/uploads/

  redis:
      image: redis:6.2.6 
      ports:
        - "6379"
        
  db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    env_file: .env.test
    cap_add:
      - SYS_NICE