version: "3.9"

services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
      # - frontend

  frontend:
    ports:
      - "3000"
    environment:
      IS_RUNNING_IN_DOCKER: 1
      NEXT_TELEMETRY_DISABLED: 1
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3000"
    depends_on:
      - db

  db:
    image: mysql:8.0.23
    ports:
      - "3306"
    
