version: "3.9"

services:
  nginx:
    volumes:
      - ./nginx/production.conf:/etc/nginx/conf.d/default.conf

  nginx-serve-static:
    build:
      context: ./nginx-serve-static/
    volumes:
      - ./storage/uploads/:/app/uploads/
      
  frontend:
    build:
      target: production
      context: ./frontend
    env_file: .env.prod
    
  backend:
    build:
      target: production
      context: ./backend
    env_file: .env.prod
    volumes: 
      - ./storage/uploads/:/app/uploads/

  redis:
    image: redis:6.2.6
    ports:
      - "6379"
      
  db:
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env.prod