version: "3.9"

services:
  nginx:
    container_name: nginx
    image: nginx
    # command: bash -c "chown -R 101:101 /mnt/storage"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./storage/uploads:/mnt/storage/uploads
    ports:
      - "80:80"

  front:
    container_name: front
    build:
      context: front
      target: development
      dockerfile: Dockerfile
    ports:
      - 3000
    volumes:
      - ./front:/app
      - /app/node_modules
      - /app/.next

  back:
    container_name: back
    build:
      context: back
      dockerfile: Dockerfile
    ports:
      - "3003"
    volumes:
      - ./storage/uploads:/app/uploads
      - ./back:/app
      - /app/node_modules
      - /app/dist
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      USER: root
      PASSWORD: "secret-pw"
      DATABASE: "nest-blog"

  db:
    container_name: mysql
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret-pw"
      MYSQL_DATABASE: "nest-blog"
    volumes:
      - ./storage/db:/var/lib/mysql
