version: "3.9"

services:
  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"

  db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    env_file: ./db/.env.dev
    cap_add:
      - SYS_NICE
