version: "3.9"

services:
  nginx:
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./storage/uploads:/mnt/storage/uploads

  frontend:
    build:
      target: development
      context: ./packages/frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

  backend:
    build:
      target: development
      context: ./packages/backend
    volumes:
      - ./backend:/app
      - ./storage/uploads:/app/uploads
      - /app/node_modules
      - /app/dist
    environment:
      DB_HOST: db
      DB_PORT: 3306
      USER: root
      PASSWORD: "secret-pw"
      DATABASE: "nest-blog"

  db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret-pw"
      MYSQL_DATABASE: "nest-blog"

