version: "3.9"

services:
  nginx:
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/front-only.conf:/etc/nginx/conf.d/default.conf
      - ./storage/uploads:/mnt/storage/uploads

  frontend:
    build:
      target: development
      context: .
      dockerfile: ./packages/frontend/Dockerfile
    volumes:
      - ./packages/frontend:/app/packages/frontend
      - ./packages/core:/app/packages/core
      - /app/node_modules
      # - /app/packages/frontend
      # - /app/.next

  backend:
    build:
      target: development
      context: .
      dockerfile: ./packages/backend/Dockerfile
    volumes:
      - ./packages/backend:/app/packages/backend
      - ./storage/uploads:/app/uploads
      - /app/node_modules
      - /app/dist
    environment:
      DB_HOST: db
      DB_PORT: 3306
      USER: root
      PASSWORD: secret-pw
      DATABASE: nest-blog
      SECRET_JWT: jA#()*%!@13

  backend_test:
    build:
      target: testing
      context: .
      dockerfile: ./packages/backend/Dockerfile
    volumes:
      - ./packages/backend:/app/packages/backend
      - ./storage/uploads:/app/uploads
      - /app/node_modules
      - /app/dist
    environment:
      DB_HOST: db
      DB_PORT: 3306
      USER: root
      PASSWORD: secret-pw
      DATABASE: nest-blog
      SECRET_JWT: jA#()*%!@13

  db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret-pw
      MYSQL_DATABASE: nest-blog
    cap_add:
      - SYS_NICE
