name: testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-test:
    env:
      working-directory: ./backend
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: ${{ env.working-directory }}

      - run: yarn install
        working-directory: ${{ env.working-directory }}

      - run: yarn build
        working-directory: ${{ env.working-directory }}

      - run: yarn test:unit
        working-directory: ${{ env.working-directory }}
    # - run: yarn test:e2e
    #   working-directory: ${{ env.working-directory }}

  frontend-test:
    env:
      working-directory: ./frontend
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: ${{ env.working-directory }}

      - run: yarn install
        working-directory: ${{ env.working-directory }}

      # - run: yarn build
      #   working-directory: ${{ env.working-directory }}

      - run: yarn test:unit
        working-directory: ${{ env.working-directory }}
    # - run: yarn test:e2e
    #   working-directory: ${{ env.working-directory }}
